# Generated by Django 6.0.2 on 2026-02-12 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_name', models.CharField(max_length=100, verbose_name='Opponent Name')),
                ('game_date', models.DateField(verbose_name='Game Date')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Venue')),
                ('team_score', models.IntegerField(verbose_name='Team Score')),
                ('opponent_score', models.IntegerField(verbose_name='Opponent Score')),
                ('q1_team', models.IntegerField(default=0, verbose_name='Q1 Team Score')),
                ('q1_opponent', models.IntegerField(default=0, verbose_name='Q1 Opponent Score')),
                ('q2_team', models.IntegerField(default=0, verbose_name='Q2 Team Score')),
                ('q2_opponent', models.IntegerField(default=0, verbose_name='Q2 Opponent Score')),
                ('q3_team', models.IntegerField(default=0, verbose_name='Q3 Team Score')),
                ('q3_opponent', models.IntegerField(default=0, verbose_name='Q3 Opponent Score')),
                ('q4_team', models.IntegerField(default=0, verbose_name='Q4 Team Score')),
                ('q4_opponent', models.IntegerField(default=0, verbose_name='Q4 Opponent Score')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('notes', models.TextField(blank=True, verbose_name='Game Notes')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorded_games', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='teams.team', verbose_name='Team')),
            ],
            options={
                'db_table': 'game',
                'ordering': ['-game_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.IntegerField(default=0, verbose_name='Minutes Played')),
                ('points', models.IntegerField(default=0, verbose_name='Points')),
                ('assists', models.IntegerField(default=0, verbose_name='Assists')),
                ('rebounds', models.IntegerField(default=0, verbose_name='Rebounds')),
                ('steals', models.IntegerField(default=0, verbose_name='Steals')),
                ('blocks', models.IntegerField(default=0, verbose_name='Blocks')),
                ('turnovers', models.IntegerField(default=0, verbose_name='Turnovers')),
                ('fouls', models.IntegerField(default=0, verbose_name='Fouls')),
                ('field_goals_made', models.IntegerField(default=0, verbose_name='Field Goals Made')),
                ('field_goals_attempted', models.IntegerField(default=0, verbose_name='Field Goals Attempted')),
                ('three_points_made', models.IntegerField(default=0, verbose_name='3-Pointers Made')),
                ('three_points_attempted', models.IntegerField(default=0, verbose_name='3-Pointers Attempted')),
                ('free_throws_made', models.IntegerField(default=0, verbose_name='Free Throws Made')),
                ('free_throws_attempted', models.IntegerField(default=0, verbose_name='Free Throws Attempted')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Recorded At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='games.game', verbose_name='Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to='teams.teammember', verbose_name='Player')),
            ],
            options={
                'db_table': 'player_stat',
                'ordering': ['-game__game_date'],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['team', 'game_date'], name='game_team_id_9b2b48_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['game_date'], name='game_game_da_c62dff_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['recorded_by'], name='game_recorde_934829_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['player', 'game'], name='player_stat_player__d428d0_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['game'], name='player_stat_game_id_7a87af_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['player'], name='player_stat_player__a15294_idx'),
        ),
        migrations.AddIndex(
            model_name='playerstat',
            index=models.Index(fields=['points'], name='player_stat_points_483f7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstat',
            unique_together={('game', 'player')},
        ),
    ]
