# Generated by Django 6.0.2 on 2026-02-12 21:01

import apps.teams.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('join_code', models.CharField(default=apps.teams.models.generate_join_code, editable=False, max_length=20, unique=True, verbose_name='Join Code')),
                ('description', models.TextField(blank=True, verbose_name='Team Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'db_table': 'team',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, null=True, verbose_name='Position')),
                ('jersey_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Jersey Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Member')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'team_member',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='team_name_53aa8f_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['join_code'], name='team_join_co_fc5aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_by'], name='team_created_573587_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user', 'team'], name='team_member_user_id_50a3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team'], name='team_member_team_id_d51a09_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['user'], name='team_member_user_id_aff06c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('user', 'team')},
        ),
    ]
