# Generated by Django 6.0.2 on 2026-02-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('COACH', 'Coach/Admin'), ('PLAYER', 'Player')], default='PLAYER', max_length=10, verbose_name='Team Role'),
        ),
    ]
