# Generated by Django 6.0.2 on 2026-02-15 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('user', 'team')},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jersey Number'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'jersey_number'), ('user', 'team')},
        ),
    ]
