# Generated by Django 6.0.2 on 2026-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('COACH', 'Coach/Admin'), ('PLAYER', 'Player')], default='PLAYER', max_length=10, null=True, verbose_name='User Role'),
        ),
    ]
