# Generated by Django 6.0.2 on 2026-02-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='custom_user_user_ty_dbe6e2_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
